FROM node:18-alpine AS build

WORKDIR /app

COPY ./frontend/portfolio/package.json ./frontend/portfolio/yarn.lock ./

RUN yarn install

COPY ./frontend/portfolio .

ENTRYPOINT ["/app/entrypoint.sh"]


RUN yarn build

# Stage 2: Serve the React application with Nginx
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY ./compose/prod/nginx/nginx.http.conf /etc/nginx/nginx.http.conf
COPY ./compose/prod/nginx/nginx.https.conf /etc/nginx/nginx.https.conf

COPY ./compose/prod/nginx/entrypoint.sh /app/entrypoint.sh
RUN ls -la /app
RUN chmod +x /app/entrypoint.sh
RUN ls -la /app/entrypoint.sh