FROM python:latest

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc

COPY ../backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ../backend .


RUN python manage.py collectstatic --noinput

EXPOSE 8000
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]